#!/usr/bin/env python
# -*- coding: utf-8 -*-

e = set((
  "                 European Union ",
  "                 Former Soviet Union",
  "                 Non-OECD",
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Canada",
  "Chile",
  "China",
  "China Hong Kong SAR",
  "Colombia",
  "Czech Republic",
  "Denmark",
  "Ecuador",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Israel",
  "Italy",
  "Japan",
  "Kazakhstan",
  "Kuwait",
  "Lithuania",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Norway",
  "of which: OECD",
  "Other Africa",
  "Other Asia Pacific",
  "Other Europe & Eurasia",
  "Other Middle East",
  "Other S. & Cent. America",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of Ireland",
  "Romania",
  "Russian Federation",
  "Saudi Arabia",
  "Singapore",
  "Slovakia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Total Africa",
  "Total Asia Pacific",
  "Total Europe & Eurasia",
  "Total Middle East",
  "Total North America",
  "Total S. & Cent. America",
  "Total World",
  "Trinidad & Tobago",
  "Turkey",
  "Turkmenistan",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "US",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
))

p = set((
  "Afghanistan",
  "AFRICA",
  "Albania",
  "Algeria",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "ASIA",
  "Australia",
  "Australia/New Zealand",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Caribbean",
  "Central African Republic",
  "Central America",
  "Central Asia",
  "Chad",
  "Channel Islands",
  "Chile",
  "China",
  "China, Hong Kong SAR",
  "China, Macao SAR",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Dem. People's Republic of Korea",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Eastern Africa",
  "Eastern Asia",
  "Eastern Europe",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "EUROPE",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "LATIN AMERICA AND THE CARIBBEAN",
  "Latvia",
  "Least developed countries",
  "Lebanon",
  "Lesotho",
  "Less developed regions",
  "Less developed regions, excluding China",
  "Less developed regions, excluding least developed countries",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Melanesia",
  "Mexico",
  "Micronesia",
  "Micronesia (Fed. States of)",
  "Middle Africa",
  "Mongolia",
  "Montenegro",
  "More developed regions",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Northern Africa",
  "NORTHERN AMERICA",
  "Northern Europe",
  "Norway",
  "OCEANIA",
  "Oman",
  "Other non-specified areas",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Polynesia",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of Korea",
  "Republic of Moldova",
  "Réunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South America",
  "South Sudan",
  "South-Central Asia",
  "South-Eastern Asia",
  "Southern Africa",
  "Southern Asia",
  "Southern Europe",
  "Spain",
  "Sri Lanka",
  "State of Palestine",
  "Sub-Saharan Africa",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Tajikistan",
  "TFYR Macedonia",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United Republic of Tanzania",
  "United States of America",
  "United States Virgin Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Western Africa",
  "Western Asia",
  "Western Europe",
  "Western Sahara",
  "WORLD",
  "Yemen",
  "Zambia",
  "Zimbabwe",
))

for i in sorted(e - p):
  print i
