\section{Beschreibende Statistik}

Analyse der Daten inkl. Tabellen und Grafiken.


\subsection{Diverses}

\subsubsection{Mittelwert}

<<echo=FALSE>>=
e_2010_total <- e[e$area == 'Total World' & e$year == 2010, c('consumption')]

n_countries <- 250

e_2010_mean <- e_2010_total / n_countries
@

Mittlerer Energiekonsum pro Land im Jahr 2010: (BESSER: Energiekonsum pro Kopf in der USA in 2010)

\begin{align*}
= \frac{\text{Weltweiter Energiekonsum im Jahr 2010}}{\text{Anzahl Länder}} = \frac{\Sexpr{e_2010_total}}{\Sexpr{n_countries}} = \Sexpr{e_2010_mean}
\end{align*}


\subsection{Eindimensionale Häufigkeitsverteilungen}


\subsection{Kumulierte Häufigkeiten und empirische Verteilungsfunktion}


\subsection{Lageparameter}


\subsection{Streuungsparameter}


\subsection{Zweidimensionale Häufigkeitsverteilungen}


\subsection{Korrelationsrechnung}


\subsection{Regressionsrechnung}
